### ISSUE TITLE
Plugin disabled, won't enable in the control panel and won't work

### ISSUE THREAD

**Issue by jayhlee** [focuslabllc/craft-cheat-sheet#41]
My cheatsheet no longer works after adding SSL on my domain and enabling HTTP2. It worked fine before the updates. Strangely, the plugin shows in my control panel but shows as disabled. When I try to click on Enable, it doesn't work. Is there perhaps an issue with using cheatsheet with SSL? I have dev mode enabled as well, so I know that's not the issue.

**Comment by dsp303** [comment]
Same here (without SSL) – Plugin won’t get active, is disabled all the time…

**Comment by erikreagan** [comment]
@jayhlee @dsp303 Good to know. We'll take a look today. Thanks!

**Comment by erikreagan** [comment]
@jayhlee @dsp303 What versions of Craft and the Cheat Sheet are you using?

**Comment by dsp303** [comment]
Craft CMS 2.6.2966, Cheat Sheat 1.2.0

**Comment by jayhlee** [comment]
@erikreagan Thanks! I'm running Craft 2.6.2966, Cheat Sheet 1.2.0.

**Comment by dfravel** [comment]
Hey guys - I believe the issue is related to the differences between the file name and the name of the class. The file name is cheatSheetPlugin.php (lower case C). However the class name is CheatSheetPlugin (upper case C). I updated on this end to be the same (ucase C) and it now works perfectly in dev and staging. FYI - I'm using Laravel Forge/Digital Ocean for Staging


![file-name](https://cloud.githubusercontent.com/assets/6830595/24098898/2095526e-0d43-11e7-8d87-f7aaea7a0d74.png)

**Comment by erikreagan** [comment]
@dfravel Ahhh excellent catch!

@dsp303 andor @jayhlee can either of you give this manual fix a try and see if it resolved the issue for you locally as well? (I've still had trouble reproducing it.)

Thanks all!

**Comment by dsp303** [comment]
Damn, that was easy – good job @dfravel! Works now after renaming the php file to "CheatSheetPlugin.php".
![screenshot](https://cloud.githubusercontent.com/assets/26271807/24099943/1262b0d6-0d72-11e7-818a-b226cfbe6675.png)

**Comment by erikreagan** [comment]
1.2.1 is pushed out and ready for download. Thanks again @dfravel!
